// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgOTDA7QD55IXK4YNe9oi9AK6sx8jmlQg',
    appId: '1:582793431937:web:edab056dbffd7e9ac7b680',
    messagingSenderId: '582793431937',
    projectId: 'pharmacy-b28fe',
    authDomain: 'pharmacy-b28fe.firebaseapp.com',
    storageBucket: 'pharmacy-b28fe.appspot.com',
    measurementId: 'G-SYFVBF1N5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7yyno7pEehLlnbRtFUkiM5bgj0lD1m0o',
    appId: '1:582793431937:android:51a365cf61a80609c7b680',
    messagingSenderId: '582793431937',
    projectId: 'pharmacy-b28fe',
    storageBucket: 'pharmacy-b28fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa6TeKlBnb3GylYHmoZGPasoWJJVmgbtg',
    appId: '1:582793431937:ios:1fc51606aca4114dc7b680',
    messagingSenderId: '582793431937',
    projectId: 'pharmacy-b28fe',
    storageBucket: 'pharmacy-b28fe.appspot.com',
    iosBundleId: 'com.example.pharmacyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa6TeKlBnb3GylYHmoZGPasoWJJVmgbtg',
    appId: '1:582793431937:ios:21e0d79e0778c999c7b680',
    messagingSenderId: '582793431937',
    projectId: 'pharmacy-b28fe',
    storageBucket: 'pharmacy-b28fe.appspot.com',
    iosBundleId: 'com.example.pharmacyApp.RunnerTests',
  );
}
